In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_excel("data/asthma_exacerbation_dataset.xlsx")
print("Shape: ", df.shape)
df.head()

Shape:  (195, 25)

,id,t,Asthma exacerbation,Gender,agecat,bmicat,Breastfeed,Smokingpre,Rhinitis,Eczema,...,Ath,FVCcat,FEV1cat,REVcat,ACTcat,ataq,ACTds,ACTda,NocSym,Dyspnea
0,1,1,No Exacerbation,Male,Pre-school,Normal,Yes,No,Yes,Eczema,...,8,FVC: Normal activity,FEV1: Normal,Non Significant,Good asthma control,ATAQ=0,Daily symptoms,No Daily activities symptoms,No Nocturnal Symptoms,No
1,1,2,Exacerbation,Male,Gradeschooler,Normal,Yes,No,Yes,Eczema,...,8,FVC: Normal activity,FEV1: Normal,Non Significant,Good asthma control,ATAQ=0,No Daily symptoms,No Daily activities symptoms,No Nocturnal Symptoms,No
2,2,1,No Exacerbation,Male,Gradeschooler,Obese,Yes,No,No,No Eczema,...,3,FVC: Normal activity,FEV1: Normal,Non Significant,Moderate asthma control,ATAQ=1,No Daily symptoms,No Daily activities symptoms,No Nocturnal Symptoms,No
3,2,2,No Exacerbation,Male,Gradeschooler,Obese,Yes,No,No,No Eczema,...,3,FVC: Normal activity,FEV1: Normal,Non Significant,Good asthma control,ATAQ=0,Daily symptoms,Daily activities symptoms,No Nocturnal Symptoms,No
4,2,3,No Exacerbation,Male,Gradeschooler,Obese,Yes,No,No,No Eczema,...,3,FVC: Normal activity,FEV1: Normal,Non Significant,Moderate asthma control,ATAQ=1,No Daily symptoms,No Daily activities symptoms,No Nocturnal Symptoms,No

In [6]:
print(df.columns.tolist())

['id', 't', 'Asthma exacerbation', 'Gender', 'agecat', 'bmicat', 'Breastfeed', 'Smokingpre', 'Rhinitis', 'Eczema', 'Bronch', 'Asthmacat', 'Foodalle', 'Drugsalle', 'Animalshom', 'Ath', 'FVCcat', 'FEV1cat', 'REVcat', 'ACTcat', 'ataq', 'ACTds', 'ACTda', 'NocSym', 'Dyspnea']

In [7]:
df["Asthma exacerbation"].value_counts()

Asthma exacerbation
No Exacerbation    166
Exacerbation        29
Name: count, dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   195 non-null    int64
 1   t                    195 non-null    int64
 2   Asthma exacerbation  195 non-null    str
 3   Gender               195 non-null    str
 4   agecat               195 non-null    str
 5   bmicat               195 non-null    str
 6   Breastfeed           195 non-null    str
 7   Smokingpre           195 non-null    str
 8   Rhinitis             195 non-null    str
 9   Eczema               195 non-null    str
 10  Bronch               195 non-null    str
 11  Asthmacat            195 non-null    str
 12  Foodalle             195 non-null    str
 13  Drugsalle            195 non-null    str
 14  Animalshom           195 non-null    str
 15  Ath                  195 non-null    int64
 16  FVCcat               195 non-null    str
 17  FEV1cat              195 non-null    str
 18  REVcat               195 non-null    str
 19  ACTcat               195 non-null    str
 20  ataq                 195 non-null    str
 21  ACTds                195 non-null    str
 22  ACTda                195 non-null    str
 23  NocSym               195 non-null    str
 24  Dyspnea              195 non-null    str
dtypes: int64(3), str(22)
memory usage: 38.2 KB

In [9]:
for col in df.columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- id ---
id
2     4
5     4
6     4
26    4
28    4
     ..
42    2
43    2
46    2
52    2
53    2
Name: count, Length: 65, dtype: int64

--- t ---
t
1    65
2    65
3    53
4    12
Name: count, dtype: int64

--- Asthma exacerbation ---
Asthma exacerbation
No Exacerbation    166
Exacerbation        29
Name: count, dtype: int64

--- Gender ---
Gender
Male      126
Female     69
Name: count, dtype: int64

--- agecat ---
agecat
Gradeschooler    137
Pre-school        25
Toddler           25
Highschooler       8
Name: count, dtype: int64

--- bmicat ---
bmicat
Normal         81
Obese          69
Overweight     39
Underweight     6
Name: count, dtype: int64

--- Breastfeed ---
Breastfeed
Yes    155
No      40
Name: count, dtype: int64

--- Smokingpre ---
Smokingpre
No     163
Yes     32
Name: count, dtype: int64

--- Rhinitis ---
Rhinitis
Yes    155
No      40
Name: count, dtype: int64

--- Eczema ---
Eczema
No Eczema    176
Eczema        19
Name: count, dtype: int64

--- Bronch ---
Bronch
No     119
Yes     76
Name: count, dtype: int64

--- Asthmacat ---
Asthmacat
Intermittent    99
Persistent      96
Name: count, dtype: int64

--- Foodalle ---
Foodalle
No Food Allergies    173
Food Allergies        22
Name: count, dtype: int64

--- Drugsalle ---
Drugsalle
No     161
Yes     34
Name: count, dtype: int64

--- Animalshom ---
Animalshom
No     117
Yes     78
Name: count, dtype: int64

--- Ath ---
Ath
0     103
2      23
5      21
1      14
3      10
7       9
4       4
11      3
6       3
9       3
8       2
Name: count, dtype: int64

--- FVCcat ---
FVCcat
FVC: Normal activity    151
FVC: Hypoactivity        44
Name: count, dtype: int64

--- FEV1cat ---
FEV1cat
FEV1: Normal          170
FEV1: Hypoactivity     25
Name: count, dtype: int64

--- REVcat ---
REVcat
Non Significant    186
Significant          9
Name: count, dtype: int64

--- ACTcat ---
ACTcat
Good asthma control        132
Moderate asthma control     58
Poor asthma control          5
Name: count, dtype: int64

--- ataq ---
ataq
ATAQ=0    134
ATAQ=1     50
ATAQ=2      6
ATAQ=3      5
Name: count, dtype: int64

--- ACTds ---
ACTds
No Daily symptoms    158
Daily symptoms        37
Name: count, dtype: int64

--- ACTda ---
ACTda
No Daily activities symptoms    162
Daily activities symptoms        33
Name: count, dtype: int64

--- NocSym ---
NocSym
No Nocturnal Symptoms    183
Nocturnal Symptoms        12
Name: count, dtype: int64

--- Dyspnea ---
Dyspnea
No     191
Yes      4
Name: count, dtype: int64

In [10]:
print(df.groupby("id")["t"].count().value_counts().sort_index())

t
2    12
3    41
4    12
Name: count, dtype: int64

In [11]:
print(df.groupby("t")["Asthma exacerbation"].value_counts())

t  Asthma exacerbation
1  No Exacerbation        57
   Exacerbation            8
2  No Exacerbation        55
   Exacerbation           10
3  No Exacerbation        42
   Exacerbation           11
4  No Exacerbation        12
Name: count, dtype: int64

Let's understand the actual relationship between the target and the variables.

In [ ]:
#gender and exacerbation
pd.crosstab(df["Asthma exacerbation"], df["Gender"])

Gender               Female  Male
Asthma exacerbation
Exacerbation              9    20
No Exacerbation          60   106

In [ ]:
#age category and exacerbation
pd.crosstab(df["Asthma exacerbation"], df["agecat"])

agecat               Gradeschooler  Highschooler  Pre-school  Toddler
Asthma exacerbation
Exacerbation                    17             2           6        4
No Exacerbation                120             6          19       21

In [ ]:
#BMI category and exacerbation
pd.crosstab(df["Asthma exacerbation"], df["bmicat"])

bmicat               Normal  Obese  Overweight  Underweight
Asthma exacerbation
Exacerbation             15     10           3            1
No Exacerbation          66     59          36            5

In [22]:
#Asthma Control Test category and exacerbation

pd.crosstab(df["Asthma exacerbation"], df["ACTcat"])

ACTcat,Good asthma control,Moderate asthma control,Poor asthma control
Asthma exacerbation,,,
Exacerbation,7,18,4
No Exacerbation,125,40,1

In [23]:
#FEV1 category and exacerbation

pd.crosstab(df["Asthma exacerbation"], df["FEV1cat"])

FEV1cat              FEV1: Hypoactivity  FEV1: Normal
Asthma exacerbation
Exacerbation                          4            25
No Exacerbation                      21           145

In [24]:
#FVC category and exacerbation

pd.crosstab(df["Asthma exacerbation"], df["FVCcat"])

FVCcat               FVC: Hypoactivity  FVC: Normal activity
Asthma exacerbation
Exacerbation                         7                    22
No Exacerbation                     37                   129

In [28]:
#FEV1 Reversibility and Exacerbation

pd.crosstab(df["Asthma exacerbation"], df["REVcat"])

REVcat               Non Significant  Significant
Asthma exacerbation
Exacerbation                      27            2
No Exacerbation                  159            7

In [29]:
#Daily Symptoms and Exacerbation

pd.crosstab(df["Asthma exacerbation"], df["ACTds"])

ACTds                Daily symptoms  No Daily symptoms
Asthma exacerbation
Exacerbation                     16                 13
No Exacerbation                  21                145

In [31]:
#Daily activity and Exacerbation

pd.crosstab(df["Asthma exacerbation"], df["ACTda"])

ACTda                Daily activities symptoms  No Daily activities symptoms
Asthma exacerbation
Exacerbation                                17                            12
No Exacerbation                             16                           150

In [33]:
#Nocturnal Symptoms and Exacerbation

pd.crosstab(df["Asthma exacerbation"], df["NocSym"])

NocSym               No Nocturnal Symptoms  Nocturnal Symptoms
Asthma exacerbation
Exacerbation                            21                   8
No Exacerbation                        162                   4

In [36]:
#Dyspnea and Exacerbation

pd.crosstab(df["Asthma exacerbation"], df["Dyspnea"])

Dyspnea               No  Yes
Asthma exacerbation
Exacerbation          26    3
No Exacerbation      165    1

In [37]:
df["Ath"].describe()

count    195.000000
mean       1.887179
std        2.660825
min        0.000000
25%        0.000000
50%        0.000000
75%        3.000000
max       11.000000
Name: Ath, dtype: float64

In [40]:
#Athma history and Exacerbation

pd.crosstab(df["Ath"], df["Asthma exacerbation"])

Asthma exacerbation  Exacerbation  No Exacerbation
Ath
0                              21               82
1                               0               14
2                               4               19
3                               0               10
4                               0                4
5                               2               19
6                               0                3
7                               0                9
8                               1                1
9                               0                3
11                              1                2

In [41]:
df.nunique().sort_values()

Gender                  2
Asthma exacerbation     2
Breastfeed              2
Smokingpre              2
Asthmacat               2
Bronch                  2
Eczema                  2
Rhinitis                2
Foodalle                2
Drugsalle               2
Animalshom              2
NocSym                  2
ACTds                   2
REVcat                  2
FEV1cat                 2
FVCcat                  2
Dyspnea                 2
ACTda                   2
ACTcat                  3
ataq                    4
bmicat                  4
t                       4
agecat                  4
Ath                    11
id                     65
dtype: int64

In [42]:
df.duplicated().sum()

np.int64(0)

In [43]:
df.columns.tolist()

['id',
 't',
 'Asthma exacerbation',
 'Gender',
 'agecat',
 'bmicat',
 'Breastfeed',
 'Smokingpre',
 'Rhinitis',
 'Eczema',
 'Bronch',
 'Asthmacat',
 'Foodalle',
 'Drugsalle',
 'Animalshom',
 'Ath',
 'FVCcat',
 'FEV1cat',
 'REVcat',
 'ACTcat',
 'ataq',
 'ACTds',
 'ACTda',
 'NocSym',
 'Dyspnea']

In [44]:
target = "Asthma exacerbation"

X = df.drop(columns=[target, "id"])
y = df[target]

print("Features:", X.columns.tolist())
print("Target:", y.name)
print("Feature shape:", X.shape)
print("Target shape:", y.shape)

Features: ['t', 'Gender', 'agecat', 'bmicat', 'Breastfeed', 'Smokingpre', 'Rhinitis', 'Eczema', 'Bronch', 'Asthmacat', 'Foodalle', 'Drugsalle', 'Animalshom', 'Ath', 'FVCcat', 'FEV1cat', 'REVcat', 'ACTcat', 'ataq', 'ACTds', 'ACTda', 'NocSym', 'Dyspnea']
Target: Asthma exacerbation
Feature shape: (195, 23)
Target shape: (195,)

In [45]:
y.unique()

<StringArray>
['No Exacerbation', 'Exacerbation']
Length: 2, dtype: str

In [47]:
#lets understand t better

pd.crosstab(df["t"], df["Asthma exacerbation"], normalize="index") * 100

Asthma exacerbation  Exacerbation  No Exacerbation
t
1                       12.307692        87.692308
2                       15.384615        84.615385
3                       20.754717        79.245283
4                        0.000000       100.000000

In [50]:
#after dropping id and t, we have the following features and target

X = df.drop(columns=["Asthma exacerbation", "id", "t"])
y = df["Asthma exacerbation"]

print("Features:", X.columns.tolist())
print("Feature shape:", X.shape)

Features: ['Gender', 'agecat', 'bmicat', 'Breastfeed', 'Smokingpre', 'Rhinitis', 'Eczema', 'Bronch', 'Asthmacat', 'Foodalle', 'Drugsalle', 'Animalshom', 'Ath', 'FVCcat', 'FEV1cat', 'REVcat', 'ACTcat', 'ataq', 'ACTds', 'ACTda', 'NocSym', 'Dyspnea']
Feature shape: (195, 22)

In [51]:
X.dtypes

Gender          str
agecat          str
bmicat          str
Breastfeed      str
Smokingpre      str
Rhinitis        str
Eczema          str
Bronch          str
Asthmacat       str
Foodalle        str
Drugsalle       str
Animalshom      str
Ath           int64
FVCcat          str
FEV1cat         str
REVcat          str
ACTcat          str
ataq            str
ACTds           str
ACTda           str
NocSym          str
Dyspnea         str
dtype: object

In [52]:
#check whether Ath has any unusual missing/special values

X["Ath"].value_counts().sort_index()

Ath
0     103
1      14
2      23
3      10
4       4
5      21
6       3
7       9
8       2
9       3
11      3
Name: count, dtype: int64

In [53]:
from sklearn.preprocessing import OrdinalEncoder

categorical_features = X.columns.tolist()

encoder = OrdinalEncoder(
    handle_unknown="use_encoded_value",
    unknown_value=-1
)

X_encoded = encoder.fit_transform(X[categorical_features])

print("Encoded shape:", X_encoded.shape)
print("Number of features:", X_encoded.shape[1])

Encoded shape: (195, 22)
Number of features: 22

In [54]:
pd.DataFrame(
    X_encoded,
    columns=X.columns
).head()

,Gender,agecat,bmicat,Breastfeed,Smokingpre,Rhinitis,Eczema,Bronch,Asthmacat,Foodalle,...,Ath,FVCcat,FEV1cat,REVcat,ACTcat,ataq,ACTds,ACTda,NocSym,Dyspnea
0,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,8.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,8.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,3.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0
3,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,3.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,3.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0

In [55]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_encoded = label_encoder.fit_transform(y)

print("Classes:", label_encoder.classes_)
print("Encoded target:", np.unique(y_encoded))

Classes: ['Exacerbation' 'No Exacerbation']
Encoded target: [0 1]

In [56]:
from sklearn.model_selection import train_test_split

patient_ids = df["id"].unique()

train_ids, test_ids = train_test_split(
    patient_ids,
    test_size=0.20,
    random_state=42
)

print("Total patients:", len(patient_ids))
print("Training patients:", len(train_ids))
print("Testing patients:", len(test_ids))

Total patients: 65
Training patients: 52
Testing patients: 13

In [57]:
id_overlap = set(train_ids) & set(test_ids)

print("Overlapping patients:", id_overlap)
print("Number of overlapping patients:", len(id_overlap))

Overlapping patients: set()
Number of overlapping patients: 0

In [58]:
train_mask = df["id"].isin(train_ids)
test_mask = df["id"].isin(test_ids)

X_train = df.loc[train_mask].drop(columns=["id", "t", "Asthma exacerbation"])
X_test = df.loc[test_mask].drop(columns=["id", "t", "Asthma exacerbation"])

y_train = df.loc[train_mask, "Asthma exacerbation"]
y_test = df.loc[test_mask, "Asthma exacerbation"]

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (157, 22)
X_test: (38, 22)
y_train: (157,)
y_test: (38,)

In [59]:
encoder = OrdinalEncoder(
    handle_unknown="use_encoded_value",
    unknown_value=-1
)

X_train_encoded = encoder.fit_transform(X_train)
X_test_encoded = encoder.transform(X_test)

print("X_train_encoded:", X_train_encoded.shape)
print("X_test_encoded:", X_test_encoded.shape)

X_train_encoded: (157, 22)
X_test_encoded: (38, 22)

In [60]:
label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

print("Classes:", label_encoder.classes_)
print("y_train_encoded:", np.unique(y_train_encoded))
print("y_test_encoded:", np.unique(y_test_encoded))

Classes: ['Exacerbation' 'No Exacerbation']
y_train_encoded: [0 1]
y_test_encoded: [0 1]

In [61]:
print("Minimum training encoded value:", X_train_encoded.min())
print("Minimum testing encoded value:", X_test_encoded.min())

Minimum training encoded value: 0.0
Minimum testing encoded value: -1.0

In [ ]:
import numpy as np

# Number of known categories for each feature
n_categories = np.array([
    len(categories) for categories in encoder.categories_
])

# Give unseen test categories a new valid category index
for i in range(X_test_encoded.shape[1]):
    X_test_encoded[:, i] = np.where(
        X_test_encoded[:, i] == -1,
        n_categories[i],
        X_test_encoded[:, i]
    )

# Tell the model about the additional unknown category
n_categories = n_categories + 1

print("Remaining negative values:", (X_test_encoded < 0).sum())
print("Number of categories per feature:", n_categories)