In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_excel("data/asthma_exacerbation_dataset.xlsx")
print("Shape: ", df.shape)
df.head()

Shape:  (195, 25)

,id,t,Asthma exacerbation,Gender,agecat,bmicat,Breastfeed,Smokingpre,Rhinitis,Eczema,...,Ath,FVCcat,FEV1cat,REVcat,ACTcat,ataq,ACTds,ACTda,NocSym,Dyspnea
0,1,1,No Exacerbation,Male,Pre-school,Normal,Yes,No,Yes,Eczema,...,8,FVC: Normal activity,FEV1: Normal,Non Significant,Good asthma control,ATAQ=0,Daily symptoms,No Daily activities symptoms,No Nocturnal Symptoms,No
1,1,2,Exacerbation,Male,Gradeschooler,Normal,Yes,No,Yes,Eczema,...,8,FVC: Normal activity,FEV1: Normal,Non Significant,Good asthma control,ATAQ=0,No Daily symptoms,No Daily activities symptoms,No Nocturnal Symptoms,No
2,2,1,No Exacerbation,Male,Gradeschooler,Obese,Yes,No,No,No Eczema,...,3,FVC: Normal activity,FEV1: Normal,Non Significant,Moderate asthma control,ATAQ=1,No Daily symptoms,No Daily activities symptoms,No Nocturnal Symptoms,No
3,2,2,No Exacerbation,Male,Gradeschooler,Obese,Yes,No,No,No Eczema,...,3,FVC: Normal activity,FEV1: Normal,Non Significant,Good asthma control,ATAQ=0,Daily symptoms,Daily activities symptoms,No Nocturnal Symptoms,No
4,2,3,No Exacerbation,Male,Gradeschooler,Obese,Yes,No,No,No Eczema,...,3,FVC: Normal activity,FEV1: Normal,Non Significant,Moderate asthma control,ATAQ=1,No Daily symptoms,No Daily activities symptoms,No Nocturnal Symptoms,No

In [6]:
print(df.columns.tolist())

['id', 't', 'Asthma exacerbation', 'Gender', 'agecat', 'bmicat', 'Breastfeed', 'Smokingpre', 'Rhinitis', 'Eczema', 'Bronch', 'Asthmacat', 'Foodalle', 'Drugsalle', 'Animalshom', 'Ath', 'FVCcat', 'FEV1cat', 'REVcat', 'ACTcat', 'ataq', 'ACTds', 'ACTda', 'NocSym', 'Dyspnea']

In [7]:
df["Asthma exacerbation"].value_counts()

Asthma exacerbation
No Exacerbation    166
Exacerbation        29
Name: count, dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   195 non-null    int64
 1   t                    195 non-null    int64
 2   Asthma exacerbation  195 non-null    str
 3   Gender               195 non-null    str
 4   agecat               195 non-null    str
 5   bmicat               195 non-null    str
 6   Breastfeed           195 non-null    str
 7   Smokingpre           195 non-null    str
 8   Rhinitis             195 non-null    str
 9   Eczema               195 non-null    str
 10  Bronch               195 non-null    str
 11  Asthmacat            195 non-null    str
 12  Foodalle             195 non-null    str
 13  Drugsalle            195 non-null    str
 14  Animalshom           195 non-null    str
 15  Ath                  195 non-null    int64
 16  FVCcat               195 non-null    str
 17  FEV1cat              195 non-null    str
 18  REVcat               195 non-null    str
 19  ACTcat               195 non-null    str
 20  ataq                 195 non-null    str
 21  ACTds                195 non-null    str
 22  ACTda                195 non-null    str
 23  NocSym               195 non-null    str
 24  Dyspnea              195 non-null    str
dtypes: int64(3), str(22)
memory usage: 38.2 KB

In [9]:
for col in df.columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- id ---
id
2     4
5     4
6     4
26    4
28    4
     ..
42    2
43    2
46    2
52    2
53    2
Name: count, Length: 65, dtype: int64

--- t ---
t
1    65
2    65
3    53
4    12
Name: count, dtype: int64

--- Asthma exacerbation ---
Asthma exacerbation
No Exacerbation    166
Exacerbation        29
Name: count, dtype: int64

--- Gender ---
Gender
Male      126
Female     69
Name: count, dtype: int64

--- agecat ---
agecat
Gradeschooler    137
Pre-school        25
Toddler           25
Highschooler       8
Name: count, dtype: int64

--- bmicat ---
bmicat
Normal         81
Obese          69
Overweight     39
Underweight     6
Name: count, dtype: int64

--- Breastfeed ---
Breastfeed
Yes    155
No      40
Name: count, dtype: int64

--- Smokingpre ---
Smokingpre
No     163
Yes     32
Name: count, dtype: int64

--- Rhinitis ---
Rhinitis
Yes    155
No      40
Name: count, dtype: int64

--- Eczema ---
Eczema
No Eczema    176
Eczema        19
Name: count, dtype: int64

--- Bronch ---
Bronch
No     119
Yes     76
Name: count, dtype: int64

--- Asthmacat ---
Asthmacat
Intermittent    99
Persistent      96
Name: count, dtype: int64

--- Foodalle ---
Foodalle
No Food Allergies    173
Food Allergies        22
Name: count, dtype: int64

--- Drugsalle ---
Drugsalle
No     161
Yes     34
Name: count, dtype: int64

--- Animalshom ---
Animalshom
No     117
Yes     78
Name: count, dtype: int64

--- Ath ---
Ath
0     103
2      23
5      21
1      14
3      10
7       9
4       4
11      3
6       3
9       3
8       2
Name: count, dtype: int64

--- FVCcat ---
FVCcat
FVC: Normal activity    151
FVC: Hypoactivity        44
Name: count, dtype: int64

--- FEV1cat ---
FEV1cat
FEV1: Normal          170
FEV1: Hypoactivity     25
Name: count, dtype: int64

--- REVcat ---
REVcat
Non Significant    186
Significant          9
Name: count, dtype: int64

--- ACTcat ---
ACTcat
Good asthma control        132
Moderate asthma control     58
Poor asthma control          5
Name: count, dtype: int64

--- ataq ---
ataq
ATAQ=0    134
ATAQ=1     50
ATAQ=2      6
ATAQ=3      5
Name: count, dtype: int64

--- ACTds ---
ACTds
No Daily symptoms    158
Daily symptoms        37
Name: count, dtype: int64

--- ACTda ---
ACTda
No Daily activities symptoms    162
Daily activities symptoms        33
Name: count, dtype: int64

--- NocSym ---
NocSym
No Nocturnal Symptoms    183
Nocturnal Symptoms        12
Name: count, dtype: int64

--- Dyspnea ---
Dyspnea
No     191
Yes      4
Name: count, dtype: int64

In [10]:
print(df.groupby("id")["t"].count().value_counts().sort_index())

t
2    12
3    41
4    12
Name: count, dtype: int64

In [11]:
print(df.groupby("t")["Asthma exacerbation"].value_counts())

t  Asthma exacerbation
1  No Exacerbation        57
   Exacerbation            8
2  No Exacerbation        55
   Exacerbation           10
3  No Exacerbation        42
   Exacerbation           11
4  No Exacerbation        12
Name: count, dtype: int64

Let's understand the actual relationship between the target and the variables.

In [ ]:
#gender and exacerbation
pd.crosstab(df["Asthma exacerbation"], df["Gender"])

Gender               Female  Male
Asthma exacerbation
Exacerbation              9    20
No Exacerbation          60   106

In [ ]:
#age category and exacerbation
pd.crosstab(df["Asthma exacerbation"], df["agecat"])

agecat               Gradeschooler  Highschooler  Pre-school  Toddler
Asthma exacerbation
Exacerbation                    17             2           6        4
No Exacerbation                120             6          19       21

In [ ]:
#BMI category and exacerbation
pd.crosstab(df["Asthma exacerbation"], df["bmicat"])

bmicat               Normal  Obese  Overweight  Underweight
Asthma exacerbation
Exacerbation             15     10           3            1
No Exacerbation          66     59          36            5

In [22]:
#Asthma Control Test category and exacerbation

pd.crosstab(df["Asthma exacerbation"], df["ACTcat"])

ACTcat,Good asthma control,Moderate asthma control,Poor asthma control
Asthma exacerbation,,,
Exacerbation,7,18,4
No Exacerbation,125,40,1

In [23]:
#FEV1 category and exacerbation

pd.crosstab(df["Asthma exacerbation"], df["FEV1cat"])

FEV1cat              FEV1: Hypoactivity  FEV1: Normal
Asthma exacerbation
Exacerbation                          4            25
No Exacerbation                      21           145

In [24]:
#FVC category and exacerbation

pd.crosstab(df["Asthma exacerbation"], df["FVCcat"])

FVCcat               FVC: Hypoactivity  FVC: Normal activity
Asthma exacerbation
Exacerbation                         7                    22
No Exacerbation                     37                   129

In [28]:
#FEV1 Reversibility and Exacerbation

pd.crosstab(df["Asthma exacerbation"], df["REVcat"])

REVcat               Non Significant  Significant
Asthma exacerbation
Exacerbation                      27            2
No Exacerbation                  159            7

In [29]:
#Daily Symptoms and Exacerbation

pd.crosstab(df["Asthma exacerbation"], df["ACTds"])

ACTds                Daily symptoms  No Daily symptoms
Asthma exacerbation
Exacerbation                     16                 13
No Exacerbation                  21                145

In [31]:
#Daily activity and Exacerbation

pd.crosstab(df["Asthma exacerbation"], df["ACTda"])

ACTda                Daily activities symptoms  No Daily activities symptoms
Asthma exacerbation
Exacerbation                                17                            12
No Exacerbation                             16                           150

In [ ]:
#Nocturnal Symptoms and Exacerbation

pd.crosstab(df["Asthma exacerbation"], df["NocSym"])

NocSym               No Nocturnal Symptoms  Nocturnal Symptoms
Asthma exacerbation
Exacerbation                            21                   8
No Exacerbation                        162                   4